### ISSUE TITLE
Cannot print to USB/Parallel Printer

### ISSUE THREAD

**Issue by mjochocki** [OpenPymeMx/ProxyPoS#10]
I cannot print to my USB receipt printer. The info.error log shows the following:

2014-06-25 10:02:45,841 - proxypos.proxypos - INFO - ProxyPos server starting up...
2014-06-25 10:02:45,842 - proxypos.proxypos - INFO - Listening on http://localhost:8069/
2014-06-25 10:08:54,983 - proxypos.proxypos.app - INFO - open_cashbox
2014-06-25 10:08:55,208 - proxypos.proxypos.app - ERROR - Failed to open the cashbox
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/proxypos-1.2.0-py2.7.egg/proxypos/proxypos/app.py", line 259, in open_cashbox
    device = printer.device()
  File "/usr/local/lib/python2.7/dist-packages/proxypos-1.2.0-py2.7.egg/proxypos/proxypos/controlers/printer.py", line 48, in **init**
    settings['idProduct'])
  File "/usr/local/lib/python2.7/dist-packages/escpos/printer.py", line 36, in **init**
    self.open()
  File "/usr/local/lib/python2.7/dist-packages/escpos/printer.py", line 64, in open
    cfg = self.device.get_active_configuration()
  File "/usr/local/lib/python2.7/dist-packages/usb/core.py", line 785, in get_active_configuration
    return self._ctx.get_active_configuration(self)
  File "/usr/local/lib/python2.7/dist-packages/usb/core.py", line 210, in get_active_configuration
    bConfigurationValue=self.backend.get_configuration(self.handle)
  File "/usr/local/lib/python2.7/dist-packages/usb/backend/libusb0.py", line 460, in get_configuration
    100)
  File "/usr/local/lib/python2.7/dist-packages/usb/backend/libusb0.py", line 528, in ctrl_transfer
    timeout
  File "/usr/local/lib/python2.7/dist-packages/usb/backend/libusb0.py", line 380, in _check
    raise USBError(errmsg, ret)
USBError: [Errno None] error sending control message: Operation not permitted
2014-06-25 10:09:32,363 - proxypos.proxypos.app - INFO - Procesing /pos/print_receipt POST method
2014-06-25 10:09:32,365 - proxypos.proxypos.app - INFO - Printing receipt {'shop': {'name': 'Profile - PWW101 - Virtual at CNA'}, 'total_tax': 0, 'name': 'Order 1403708738650', 'total_with_tax': 49.47, 'company': {'website': False, 'name': 'Profile Enterprise', 'phone': False, 'contact_address': '\n\n  \n', 'email': 'info@profilediet.com', 'vat': False, 'company_registry': False}, 'orderlines': [{'unit_name': 'Unit(s)', 'product_description_sale': False, 'price_display': 17.490000000000002, 'price': 17.490000000000002, 'tax': 0, 'product_description': False, 'price_with_tax': 17.490000000000002, 'price_without_tax': 17.490000000000002, 'discount': 0, 'product_name': '15g MR Variety Pack', 'quantity': 1}, {'unit_name': 'Unit(s)', 'product_description_sale': False, 'price_display': 31.98, 'price': 15.99, 'tax': 0, 'product_description': False, 'price_with_tax': 31.98, 'price_without_tax': 31.98, 'discount': 0, 'product_name': 'Creamy Tomato Soup-15g', 'quantity': 2}], 'cashier': 'PWW101-Reg1', 'total_without_tax': 49.47, 'currency': {'rounding': 0.01, 'position': 'before', 'symbol': '$', 'id': 3, 'accuracy': 4}, 'client': {'membership_status': False, 'name': 'Walk in Customer', 'mobile': False, 'customer_type': False, 'walkin_customer': True, 'id': 61699, 'vat': False}, 'total_discount': 0, 'invoice_id': None, 'date': {'hour': 10, 'month': 5, 'year': 2014, 'date': 25, 'day': 3, 'minute': 9}, 'total_paid': 49.47, 'paymentlines': [{'amount': 49.47, 'journal': 'Check (USD)'}], 'subtotal': 49.47, 'change': 0}
2014-06-25 10:09:32,367 - proxypos.proxypos.app - ERROR - Failed to print receipt
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/proxypos-1.2.0-py2.7.egg/proxypos/proxypos/app.py", line 89, in do_print
    device = printer.device()
  File "/usr/local/lib/python2.7/dist-packages/proxypos-1.2.0-py2.7.egg/proxypos/proxypos/controlers/printer.py", line 48, in __init__
    settings['idProduct'])
  File "/usr/local/lib/python2.7/dist-packages/escpos/printer.py", line 36, in **init**
    self.open()
  File "/usr/local/lib/python2.7/dist-packages/escpos/printer.py", line 58, in open
    self.device.set_configuration()
  File "/usr/local/lib/python2.7/dist-packages/usb/core.py", line 779, in set_configuration
    self._ctx.managed_set_configuration(self, configuration)
  File "/usr/local/lib/python2.7/dist-packages/usb/core.py", line 126, in managed_set_configuration
    self.managed_open()
  File "/usr/local/lib/python2.7/dist-packages/usb/core.py", line 104, in managed_open
    self.handle = self.backend.open_device(self.dev)
  File "/usr/local/lib/python2.7/dist-packages/usb/backend/libusb1.py", line 718, in open_device
    return _DeviceHandle(dev)
  File "/usr/local/lib/python2.7/dist-packages/usb/backend/libusb1.py", line 596, in __init__
    _check(_lib.libusb_open(self.devid, byref(self.handle)))
  File "/usr/local/lib/python2.7/dist-packages/usb/backend/libusb1.py", line 548, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
  File "/usr/local/lib/python2.7/dist-packages/usb/backend/libusb1.py", line 537, in _strerror
    return _lib.libusb_strerror(errcode).decode('utf8')
  File "/usr/lib/python2.7/ctypes/__init__.py", line 378, in **getattr**
    func = self.**getitem**(name)
  File "/usr/lib/python2.7/ctypes/**init**.py", line 383, in **getitem**
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /lib/i386-linux-gnu/libusb-1.0.so.0: undefined symbol: libusb_strerror
2014-06-25 10:09:32,395 - proxypos.proxypos.app - INFO - Procesing /pos/print_receipt GET method
2014-06-25 10:09:32,396 - proxypos.proxypos.app - INFO - Already printed receipt by POST method
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/proxypos-1.2.0-py2.7.egg/proxypos/proxypos/app.py", line 276, in print_receipt
    logger.debug('Params %s', str(params['r']))
KeyError: 'r'

**Comment by agb80** [comment]
Would you mind share the exact model of your printer? 

According to your log seems your printer is in fact waiting a parallel protocol communication, currently parallel protocol printers are not supported.

**Comment by mjochocki** [comment]
The printer is a Wintec WIN9PT. It has the USB to Parallel circuitry built in to the printer. I have a Bixolon 350 pure USB printer that I'll try. Thanks for the help!

**Comment by agb80** [comment]
Just found information for model WIN80PT, http://detail.en.china.cn/provide/1117416314.html, but seems it only support serial/parallel communication protocol.

Parallel protocol is not currently supported, if you are interested on sponsor this feature feel free to contact us. Anyway I'm going to close this issue, feel free to open a new on if you have problems with your other USB printer.

Have a nice day!
